version: '3'
services:
  java-app:
    container_name: java-app
    image: pee-java_app
    build: .
    ports:
      - "8081:8081"

  java-api:
    container_name: java-api
    image: tupfrcutn/elecciones-2023:1.0.0
    ports:
      - "8080:8080"